export default {
	Button2CopyonClick () {
		export default {
			async () => {
				// 1. Initialize jsPDF
				const { jsPDF } = jspdf;
				const doc = new jsPDF();

				// 2. Add content (static or from widgets)
				doc.text("Report Title", 10, 10);
				doc.text(`Generated by: ${appsmith.user.name}`, 10, 20);
				doc.text(`Data from Input: ${appsmith.currentPageName }`, 10, 30);

				// 3. Generate a Data URL for the Document Viewer or direct download
				const pdfData = doc.output("dataurlstring");

				// To download directly:
				// download(pdfData, "my-report.pdf", "application/pdf");

				return pdfData; 
			}
		}

	}
}